Files already downloaded and verified
Files already downloaded and verified
Round No: 0
Traceback (most recent call last):
  File "/home/goktug/Desktop/thesis/netadapt-x-flower/fed_train_sim.py", line 633, in <module>
    global_model = federated_learning(args)
  File "/home/goktug/Desktop/thesis/netadapt-x-flower/fed_train_sim.py", line 481, in federated_learning
    client_selector = ClientSelector(
  File "/home/goktug/Desktop/thesis/netadapt-x-flower/client_selection.py", line 145, in __init__
    self.df = pd.read_csv(dataset_path)
  File "/home/goktug/python_envs/easyfl/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/goktug/python_envs/easyfl/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/goktug/python_envs/easyfl/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/goktug/python_envs/easyfl/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/goktug/python_envs/easyfl/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/32_Cifar10_NIID_56c_a03/bws.csv'